#!/usr/bin/env python3
"""Export human-approved form media for the app, without changing the catalog.

Only descriptors enter the app source tree. Approved MP4/WebP delivery copies
are served on demand from its ignored public directory; masters stay here.
"""
from __future__ import annotations

import argparse
from datetime import datetime
import hashlib
import json
from pathlib import Path
import re
import shutil
from urllib.parse import parse_qs, unquote, urlsplit

import form_media as media


def require(condition, message):
    if not condition:
        raise ValueError(message)


def timestamp(value):
    parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    require(parsed.tzinfo is not None, "Approval timestamps must include a timezone.")
    return parsed


def last_human_decision(manifest, exercise_id, asset_id):
    decisions = [entry for entry in manifest.get("reviewHistory", [])
                 if entry.get("source") in {"dashboard", "user-conditional-original-speed-trim", "user-conditional-rename"}
                 and entry.get("exerciseId") == exercise_id
                 and (asset_id in entry.get("selectedAssetIds", [])
                      or (entry.get("reviewStatus") == "rejected"
                          and asset_id in entry.get("reviewedAssetIds", [])))]
    return max(decisions, key=lambda entry: timestamp(entry["createdAt"]), default=None)


def approved(manifest, exercise_id, asset):
    decision = last_human_decision(manifest, exercise_id, asset["id"])
    if not decision or decision.get("reviewStatus") != "accepted":
        return None
    # Old-round selections deliberately do not rewrite asset flags in the
    # dashboard. An exact, later human decision is the approval authority.
    rejected_at = asset.get("rejectedAt")
    if (rejected_at and timestamp(rejected_at) > timestamp(decision["createdAt"])):
        return None
    return {"reviewId": decision["id"], "reviewedAt": decision["createdAt"],
            "roundId": decision["roundId"], "source": decision["source"]}


def delivery_file(asset, *, poster=False):
    prefix = "poster" if poster else ""
    url = asset.get("posterUrl" if poster else "url", "")
    parts = urlsplit(url)
    require(not parts.scheme and not parts.netloc and not parts.query and not parts.fragment
            and parts.path.startswith("/assets/delivery/"),
            f"{asset['id']}: only registered delivery files may be exported.")
    path = media.contained(media.MEDIA, unquote(parts.path).lstrip("/"))
    extension = ".webp" if poster else ".mp4"
    require(path.suffix == extension and path.is_file(), f"Missing {extension} delivery: {asset['id']}")
    checksum = asset.get("posterSha256" if poster else "sha256")
    require(isinstance(checksum, str) and re.fullmatch(r"[a-f0-9]{64}", checksum),
            f"Missing {prefix} hash: {asset['id']}")
    require(media.sha256(path) == checksum, f"Delivery changed since review: {asset['id']}")
    size = path.stat().st_size
    require(size == asset.get("posterBytes" if poster else "bytes"),
            f"Delivery size differs from the manifest: {asset['id']}")
    return {"sourcePath": media.relative(path), "path": path, "sha256": checksum,
            "bytes": size, "filename": checksum + extension}


def youtube_id(url):
    parts = urlsplit(url)
    if parts.scheme != "https":
        return None
    host = parts.hostname
    segments = parts.path.strip("/").split("/")
    if host == "youtu.be":
        value = segments[0]
    elif host in {"youtube.com", "www.youtube.com", "m.youtube.com", "www.youtube-nocookie.com"}:
        value = (segments[1] if len(segments) > 1 and segments[0] in {"shorts", "embed", "live"}
                 else parse_qs(parts.query).get("v", [None])[0] if segments[0] == "watch" else None)
    else:
        return None
    return value if value and re.fullmatch(r"[\w-]{11}", value) else None


TYPE_HEADER = """// Generated by SpotBotData/Scripts/export_form_media.py; do not edit by hand.
// Human dashboard approvals only. Binary media is served separately on demand.
export type ApprovedExerciseFormVideo = {
  assetId: string;
  uri: string;
  posterUri?: string;
  posterBytes?: number;
  title: string;
  alt: string;
  source: string;
  styleLabel: string;
  durationSeconds: number;
  width: number;
  height: number;
  bytes: number;
  sha256: string;
};

export type ApprovedExerciseYouTubeReference = {
  assetId: string;
  url: string;
  title: string;
  source: string;
  orientation: 'portrait' | 'landscape';
  durationSeconds?: number;
  startSeconds?: number;
  endSeconds?: number;
  note?: string;
};

export const approvedExerciseFormMedia: Record<string, {
  video?: ApprovedExerciseFormVideo;
  youtube?: ApprovedExerciseYouTubeReference;
}> = """


def export(app_root):
    app_root = app_root.resolve()
    frontend = app_root / "apps/frontend"
    require((frontend / "package.json").is_file(), "Expected a SpotBot app checkout.")
    destination = frontend / "public/exercise-media"
    module = frontend / "src/features/exercises/exerciseFormMediaData.ts"
    with media.locked():
        manifest = media.read_json(media.MANIFEST)
        catalog = media.read_json(media.ROOT / "catalog.json")
        exercises = {entry["id"]: entry for entry in catalog["exercises"]}
        assets = {entry["id"]: entry for entry in manifest["assets"]}
        require(len(assets) == len(manifest["assets"]), "Duplicate asset IDs.")
        entries = {}
        selections = []
        files = {}
        external_searches = []
        revoked_references = []
        approval_flag_overrides = []
        for exercise_id, exercise in sorted(exercises.items()):
            review = manifest["exercises"].get(exercise_id, {})
            selected = review.get("selectedAssetIds", []) if review.get("reviewStatus") == "accepted" else []
            video_assets = [assets[asset_id] for asset_id in selected if assets[asset_id]["kind"] == "video"]
            require(len(video_assets) <= 1, f"Choose one approved default video: {exercise_id}")
            entry = {}
            if video_assets:
                asset = video_assets[0]
                require(asset["exerciseId"] == exercise_id and not asset.get("exerciseRetiredAt"),
                        f"Selected video belongs to another or retired exercise: {exercise_id}")
                approval = approved(manifest, exercise_id, asset)
                require(approval, f"Selected video lacks an unrevoked human approval: {asset['id']}")
                video_file = delivery_file(asset)
                files[video_file["filename"]] = video_file
                require(all(type(asset.get(field)) in {int, float} and asset[field] > 0
                            for field in ("width", "height", "durationSeconds")),
                        f"Missing video dimensions/duration: {asset['id']}")
                video = {"assetId": asset["id"], "uri": "/exercise-media/" + video_file["filename"],
                         "title": exercise["name"] + " demonstration", "alt": asset["alt"],
                         "source": asset["source"], "styleLabel": asset.get("styleLabel", "3D"),
                         "durationSeconds": asset["durationSeconds"], "width": asset["width"],
                         "height": asset["height"], "bytes": video_file["bytes"], "sha256": video_file["sha256"]}
                if asset.get("posterUrl"):
                    poster = delivery_file(asset, poster=True)
                    files[poster["filename"]] = poster
                    video["posterUri"] = "/exercise-media/" + poster["filename"]
                    video["posterBytes"] = poster["bytes"]
                entry["video"] = video
                selections.append({"exerciseId": exercise_id, "assetId": asset["id"], "kind": "video",
                                   "approval": approval, "assetReviewStatusAtExport": asset["reviewStatus"]})
                if asset["reviewStatus"] != "accepted":
                    approval_flag_overrides.append({"exerciseId": exercise_id, "assetId": asset["id"],
                                                   "assetReviewStatus": asset["reviewStatus"], "approval": approval})
            references = []
            for asset in manifest["assets"]:
                if asset["exerciseId"] != exercise_id or asset["kind"] != "external" or asset.get("exerciseRetiredAt"):
                    continue
                approval = approved(manifest, exercise_id, asset)
                if not approval:
                    decision = last_human_decision(manifest, exercise_id, asset["id"])
                    if asset.get("reviewStatus") == "accepted" and decision and decision.get("reviewStatus") == "rejected":
                        revoked_references.append({"exerciseId": exercise_id, "assetId": asset["id"],
                                                   "reviewId": decision["id"], "reviewedAt": decision["createdAt"]})
                    continue
                if asset.get("externalKind") == "search":
                    external_searches.append({"exerciseId": exercise_id, "assetId": asset["id"],
                                              "reason": "Use the app's exercise-name form search action."})
                elif youtube_id(asset["url"]):
                    references.append((asset, approval))
            if references:
                asset, approval = max(references, key=lambda pair: (pair[0]["id"] in selected,
                                                                   timestamp(pair[1]["reviewedAt"])))
                reference = {"assetId": asset["id"], "url": asset["url"],
                             "title": exercise["name"] + " demonstration", "source": asset["source"],
                             "orientation": asset.get("orientation") or ("portrait" if asset.get("height", 0) > asset.get("width", 0) else "landscape")}
                if asset.get("durationSeconds"):
                    reference["durationSeconds"] = asset["durationSeconds"]
                segment = asset.get("recommendedSegment", {})
                for field in ("startSeconds", "endSeconds"):
                    if field in segment:
                        reference[field] = segment[field]
                # These describe meaningful differences between the reference
                # and the catalog, rather than generation/review mechanics.
                if exercise_id == "ex_lunge":
                    reference["note"] = "This demonstration adds dumbbells. The same walking sequence can be performed with bodyweight."
                elif exercise_id == "cat_cal_dead_bug":
                    reference["note"] = "Use opposite arm and leg. Each extension and return counts as one repetition, totaled across both sides."
                entry["youtube"] = reference
                selections.append({"exerciseId": exercise_id, "assetId": asset["id"], "kind": "youtube", "approval": approval})
            if entry:
                entries[exercise_id] = entry

        # Validate all source approvals and hashes before writing any output.
        destination.mkdir(parents=True, exist_ok=True)
        for filename, item in files.items():
            target = destination / filename
            if not target.is_file() or media.sha256(target) != item["sha256"]:
                temporary = target.with_suffix(target.suffix + ".tmp")
                shutil.copyfile(item["path"], temporary)
                require(media.sha256(temporary) == item["sha256"], "Copied delivery checksum differs.")
                temporary.replace(target)
        serialized = json.dumps(entries, ensure_ascii=False, indent=2)
        module.parent.mkdir(parents=True, exist_ok=True)
        module.write_text(TYPE_HEADER + serialized + ";\n", encoding="utf-8")
        file_records = [{key: value for key, value in item.items() if key != "path"}
                        for _, item in sorted(files.items())]
        release = {"schemaVersion": 1, "catalogVersion": catalog["version"], "catalogRevision": catalog["revision"],
                   "manifestSha256": media.sha256(media.MANIFEST),
                   "selectionPolicy": "Current selected video on an accepted active exercise, backed by its latest exact-asset human dashboard decision. Keep accepted direct YouTube references as alternatives. Exclude retired exercises, superseded videos, unapproved candidates and search pages from embeds.",
                   "delivery": {"mode": "on-demand-static-web", "urlPrefix": "/exercise-media/",
                                "publicDirectory": "apps/frontend/public/exercise-media",
                                "nativeBaseUrlEnvironment": "EXPO_PUBLIC_EXERCISE_MEDIA_BASE_URL",
                                "module": "apps/frontend/src/features/exercises/exerciseFormMediaData.ts",
                                "moduleSha256": hashlib.sha256(module.read_bytes()).hexdigest()},
                   "counts": {"exercisesWithVideo": sum("video" in entry for entry in entries.values()),
                              "exercisesWithYouTube": sum("youtube" in entry for entry in entries.values()),
                              "files": len(files), "totalBytes": sum(item["bytes"] for item in files.values())},
                   "approvalFlagOverrides": approval_flag_overrides, "searchOnlyReferences": external_searches,
                   "revokedReferences": revoked_references,
                   "selections": selections, "files": file_records}
        media.write_json(media.MEDIA / "app-release.json", release)
        # Only prune this tool's hash-named outputs. Original delivery files,
        # masters and any non-managed files are never removed.
        for target in destination.iterdir():
            if re.fullmatch(r"[a-f0-9]{64}\.(mp4|webp)", target.name) and target.name not in files:
                target.unlink()
        return release["counts"]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--app-root", type=Path, default=media.ROOT.parent / "SpotBot")
    args = parser.parse_args()
    print(json.dumps(export(args.app_root), indent=2))


if __name__ == "__main__":
    main()
