#!/usr/bin/env python3
"""Export catalog-wide YouTube recommendations without changing exercise contracts.

The authoring file preserves selection evidence and availability limitations.
Only the small playback descriptors enter the app; videos remain on YouTube.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from urllib.parse import parse_qs, urlsplit
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "form-media/app-reference-recommendations.json"
FIELDS = ("url", "title", "source", "orientation", "durationSeconds", "startSeconds", "endSeconds", "note")


def export(app_root: Path):
    catalog = json.loads((ROOT / "catalog.json").read_text())
    document = json.loads(SOURCE.read_text())
    active = {exercise["id"] for exercise in catalog["exercises"]}
    references = document["references"]
    ids = [reference["exerciseId"] for reference in references]
    if len(ids) != len(set(ids)):
        raise ValueError("Duplicate YouTube recommendations for a canonical exercise.")
    missing, retired = active - set(ids), set(ids) - active
    if missing or retired:
        raise ValueError(f"Recommendation coverage differs from the active catalog: missing={sorted(missing)}, inactive={sorted(retired)}")
    output = {}
    for reference in references:
        identity = reference["exerciseId"]
        url = urlsplit(reference["url"])
        segments = url.path.strip("/").split("/")
        if url.scheme != "https" or url.username or url.password:
            raise ValueError(f"{identity}: expected a public HTTPS YouTube video.")
        video_id = None
        if url.hostname == "youtu.be" and len(segments) == 1:
            video_id = segments[0]
        elif url.hostname in {"youtube.com", "www.youtube.com", "m.youtube.com"}:
            if segments == ["watch"]:
                video_id = parse_qs(url.query).get("v", [None])[0]
            elif len(segments) == 2 and segments[0] in {"shorts", "embed", "live"}:
                video_id = segments[1]
        if not video_id or not re.fullmatch(r"[\w-]{11}", video_id):
            raise ValueError(f"{identity}: a search page cannot be embedded as a recommendation.")
        if not reference.get("editorialEvidence") or not reference.get("reviewedAt"):
            raise ValueError(f"{identity}: missing recommendation provenance.")
        availability = reference.get("availability", {})
        if availability.get("videoId") != video_id or not availability.get("oembedAvailable") or not availability.get("checkedAt"):
            raise ValueError(f"{identity}: missing public embed metadata for this exact video.")
        if any(not isinstance(reference.get(field), str) or not reference[field].strip() for field in ("title", "source")):
            raise ValueError(f"{identity}: missing publisher/title.")
        if reference.get("orientation") not in {"portrait", "landscape"}:
            raise ValueError(f"{identity}: missing player orientation.")
        for field in ("durationSeconds", "startSeconds", "endSeconds"):
            if field in reference and (type(reference[field]) not in {int, float} or reference[field] < 0):
                raise ValueError(f"{identity}: invalid {field}.")
        if "endSeconds" in reference and reference["endSeconds"] <= reference.get("startSeconds", 0):
            raise ValueError(f"{identity}: excerpt must have positive duration.")
        output[identity] = {field: reference[field] for field in FIELDS if field in reference}
    destination = app_root.resolve() / "apps/frontend/src/features/exercises/exerciseYouTubeRecommendations.ts"
    if not destination.parent.is_dir():
        raise ValueError("Expected the sibling SpotBot frontend checkout.")
    header = ("// Generated by SpotBotData/Scripts/export_youtube_references.py; do not edit by hand.\n"
              "// Recommendation evidence, human selections, and check limitations stay in the authoring manifest.\n"
              "import type { ExerciseFormReference } from './exerciseFormReferences';\n\n"
              "export const exerciseYouTubeRecommendations: Record<string, ExerciseFormReference> = ")
    destination.write_text(header + json.dumps(dict(sorted(output.items())), indent=2, ensure_ascii=False) + ";\n")
    print(f"Exported YouTube recommendations for all {len(output)} active exercises to {destination}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--app-root", type=Path, default=ROOT.parent / "SpotBot")
    export(parser.parse_args().app_root)
